name: genai_env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - seaborn
    - langchain #~=0.0.352
    - pypdf
    - sentence-transformers #==2.2.2
    - huggingface_hub
    - accelerate
    - torch #~=2.1.2
    - transformers #~=4.36.2
    - faiss-cpu